### ISSUE TITLE
【严重问题】Replit似乎已经对使用此项目的Repl进行封杀

### ISSUE THREAD

**Issue by redball1017** [redball1017/Replit-v2ray#1]
如题。推测封杀的关键词可能是.env中的v2ray或xray等字符。目前的解决方案就是将这些字符替换成其他可以逃避检测的字符，如链接使用短链接跳转，更换变量名等。

**Comment by redball1017** [comment]
#2 开始测试，未检测到Repl被封，可正常使用

**Comment by redball1017** [comment]
若在有这种情况发生，我将采取把所有变量收回，变成完全的云更新（即从网站上下载完整的V2ray配置文件和变量文件。尽最大努力逃避Replit的检测）

**Comment by Misaka-blog** [comment]
> 如题。推测封杀的关键词可能是.env中的v2ray或xray等字符。目前的解决方案就是将这些字符替换成其他可以逃避检测的字符，如链接使用短链接跳转，更换变量名等。

还有shell输出的关键词

**Comment by redball1017** [comment]
> 

是的，所以我在努力去除这些关键词

**Comment by redball1017** [comment]
> > 如题。推测封杀的关键词可能是.env中的v2ray或xray等字符。目前的解决方案就是将这些字符替换成其他可以逃避检测的字符，如链接使用短链接跳转，更换变量名等。
> 
> 还有shell输出的关键词

是的
