### ISSUE TITLE
发现个问题

### ISSUE THREAD

**Issue by feixiangdao** [redball1017/Replit-v2ray#3]
运行报错，然后发现main.sh中：
./$CORE_FILE_NAME run &> ./CORE/log.log
多了 ./CORE/
修改为：
./$CORE_FILE_NAME run &>log.log
接着没有报错了，但是还是无法成功连接

**Comment by redball1017** [comment]
现已修复 https://github.com/redball1017/Replit-v2ray/commit/026af0eecf7ff081437a308948d9c2d523ca2fd6
