### ISSUE TITLE
执行时出错

### ISSUE THREAD

**Issue by hua1980** [redball1017/Replit-v2ray#6]
我于12月13日在replit中执行这个程序是出错--提示以下问题信息：
touch: cannot touch './CORE/log.log': No such file or directory
main.sh: line 41: cd: ./CORE: No such file or directory
main.sh: line 42: /home/runner/yt/CORE/log.log: No such file or directory
请问是什么原因呢，由于我对replit容器不是太熟悉。请多多指教。

**Comment by redball1017** [comment]
方便发nohup.out里面的文本给我吗？Cloudflare可能会屏蔽Replit容器的IP，认为是机器人IP。

**Comment by redball1017** [comment]
就像是这样：
Connecting to repl-assets.rd1017.top (104.21.84.206:443)
wget: server returned error: HTTP/1.1 403 Forbidden

**Comment by hua1980** [comment]
以下是nohup.out里面的内容：
Connecting to repl-assets.rd1017.top (172.67.197.27:443)
saving to './var'
var&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 100% |********************************|&nbsp; &nbsp;109&nbsp; 0:00:00 ETA
'./var' saved
wget: bad address 'short-url.redball1017.tk'

&nbsp;


hua
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月14日(星期四) 晚上7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redball1017/Replit-v2ray] 执行时出错 (Issue #6)





 
方便发nohup.out里面的文本给我吗？Cloudflare可能会屏蔽Replit容器的IP，认为是机器人IP。

**Comment by hua1980** [comment]
这是运行后截个图
&nbsp;


hua
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月14日(星期四) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redball1017/Replit-v2ray] 执行时出错 (Issue #6)





 
就像是这样：
 Connecting to repl-assets.rd1017.top (104.21.84.206:443)
 wget: server returned error: HTTP/1.1 403 Forbidden

**Comment by redball1017** [comment]
> 这是运行后截个图 &nbsp; hua ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年12月14日(星期四) 晚上8:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [redball1017/Replit-v2ray] 执行时出错 (Issue #6) 就像是这样： Connecting to repl-assets.rd1017.top (104.21.84.206:443) wget: server returned error: HTTP/1.1 403 Forbidden — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你确定你现在的repo是最新的吗？最新版wget的URI没有short-url.redball1017.tk
